### ISSUE TITLE
[BUG] pacote ignores npm config's cache settings

### ISSUE THREAD

**Issue by BurnerWah** [npm/pacote#385] opened 2024-09-04 18:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

pacote uses the cache defined in the user's npmrc (in my case, `${XDG_CACHE_HOME}/npm`) or the `npm_config_cache` environment variable, and only uses `~/.npm` if neither of those are set.

### Expected Behavior

pacote always uses `~/.npm` for the cache

### Steps To Reproduce

1. Set a custom cache directory in the user's npmrc
2. Use pacote i guess

I noticed this while using npq, but I can tell that the bug is just here - https://github.com/npm/pacote/blob/main/lib/util/cache-dir.js
It's not checking the user config or anything like that at all

### Environment

- npm: 10.5.0 (fedora package), 10.8.2 (homebrew)
- Node: 20.12.2 (fedora package), 22.8.0 (homebrew)
- OS: Fedora 40 Workstation, Mac OS Sonoma 14.6.1
- platform: Dell G-15 Ryzen Edition, M1 Macbook Pro

**Comment by wraithgar** [comment] 2024-09-04 21:17
Did you perhaps swap the expected/current behavior in this ticket?

pacote does not parse `npmrc` files.  It expects to be told what to do, with a sensible default.  The cache is set by opts [here](https://github.com/npm/pacote/blob/39643f1e956f83dd84f7f0ab6278f7051a69b32d/lib/fetcher.js#L50), with the cacheDir code you linked to being used for defaults.

If you want to parse `npmrc`, or any of the other things that npm does in order to set up the config that it passes to `pacote` you can use `@npmcli/config`.  As of now I think pacote is working as intended.  We do not plan on adding `npmrc` parsing to this module, that's out of scope.

**Closed by wraithgar** 2024-09-04 21:17 UTC
Labels: Needs Triage, Bug

**Comment by BurnerWah** [comment] 2024-09-13 21:41
> Did you perhaps swap the expected/current behavior in this ticket?

I'll be honest I felt that was a tad bit more rude than was needed

I'll be sure to not waste my time here again

**Comment by wraithgar** [comment] 2024-09-16 06:00
Sorry, it was not intended to be rude.  I was very confused trying to parse the issue and the only explanation that made sense was that those two fields were swapped.  I triaged w/ that assumption.

Again though, this does not appear to be a pacote bug.  It puts the cache where it's told, and does not parse config files on its own.  That would have to be done by the upstream consumer.  This is usually npm.  If you have a reproduction case that shows that npm itself is not passing this config properly feel free to open an issue w/ reproduction steps so this can be fixed.
